package cfig.p2phunter.th

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * Author: cfig (yuyezhong@gmail.com))
 * Created on: 10/5/17
 */
data class HunterCreditRulesResp(
        @JsonProperty("status") var status: Int = 0,
        @JsonProperty("msg") var msg: String = "",
        @JsonProperty("count") var count: Int = 0,
        @JsonProperty("sys") var sys: MutableList<CreditRuleItem> = mutableListOf()
) {
    data class CreditRuleItem(
            @JsonProperty("StrategyId") var StrategyId: String = "",
            @JsonProperty("UserId") var UserId: String = "",
            @JsonProperty("StrategyLevel") var StrategyLevel: String = "",
            @JsonProperty("StrategyName") var StrategyName: String = "",
            @JsonProperty("Description") var Description: String = "",
            @JsonProperty("AmountA") var AmountA: String = "",
            @JsonProperty("AmountB") var AmountB: String = "",
            @JsonProperty("MonthA") var MonthA: String = "",
            @JsonProperty("MonthB") var MonthB: String = "",
            @JsonProperty("RateA") var RateA: String = "",
            @JsonProperty("RateB") var RateB: String = "",
            @JsonProperty("Credit") var Credit: String = "",
            @JsonProperty("CertificateValidate") var CertificateValidate: String = "",
            @JsonProperty("CreditValidate") var CreditValidate: String = "",
            @JsonProperty("EducateValidate") var EducateValidate: String = "",
            @JsonProperty("VideoValidate") var VideoValidate: String = "",
            @JsonProperty("PhoneValidate") var PhoneValidate: String = "",
            @JsonProperty("NciicIdentityCheck") var NciicIdentityCheck: String = "",
            @JsonProperty("Degree") var Degree: String = "",
            @JsonProperty("StudyStyle") var StudyStyle: String = "",
            @JsonProperty("School") var School: String = "",
            @JsonProperty("Gender") var Gender: String = "",
            @JsonProperty("Age") var Age: String = "",
            @JsonProperty("LastSuccessIntervalA") var LastSuccessIntervalA: String = "",
            @JsonProperty("LastSuccessIntervalB") var LastSuccessIntervalB: String = "",
            @JsonProperty("FirstSuccessIntervalA") var FirstSuccessIntervalA: String = "",
            @JsonProperty("FirstSuccessIntervalB") var FirstSuccessIntervalB: String = "",
            @JsonProperty("SuccessCountA") var SuccessCountA: String = "",
            @JsonProperty("SuccessCountB") var SuccessCountB: String = "",
            @JsonProperty("WasteCountA") var WasteCountA: String = "",
            @JsonProperty("WasteCountB") var WasteCountB: String = "",
            @JsonProperty("NormalCountA") var NormalCountA: String = "",
            @JsonProperty("NormalCountB") var NormalCountB: String = "",
            @JsonProperty("NormalSuccessRatioA") var NormalSuccessRatioA: String = "",
            @JsonProperty("NormalSuccessRatioB") var NormalSuccessRatioB: String = "",
            @JsonProperty("DelayNormalRatioA") var DelayNormalRatioA: String = "",
            @JsonProperty("DelayNormalRatioB") var DelayNormalRatioB: String = "",
            @JsonProperty("OverdueCountA") var OverdueCountA: String = "",
            @JsonProperty("OverdueCountB") var OverdueCountB: String = "",
            @JsonProperty("OverdueMoreCountA") var OverdueMoreCountA: String = "",
            @JsonProperty("OverdueMoreCountB") var OverdueMoreCountB: String = "",
            @JsonProperty("OwingAmountA") var OwingAmountA: String = "",
            @JsonProperty("OwingAmountB") var OwingAmountB: String = "",
            @JsonProperty("OwingPrevHighDebtRatioA") var OwingPrevHighDebtRatioA: String = "",
            @JsonProperty("OwingPrevHighDebtRatioB") var OwingPrevHighDebtRatioB: String = "",
            @JsonProperty("OwingHighDebtRatioA") var OwingHighDebtRatioA: String = "",
            @JsonProperty("OwingHighDebtRatioB") var OwingHighDebtRatioB: String = "",
            @JsonProperty("LastHighestBorrowRatioA") var LastHighestBorrowRatioA: String = "",
            @JsonProperty("LastHighestBorrowRatioB") var LastHighestBorrowRatioB: String = "",
            @JsonProperty("BidAmount") var BidAmount: String = "",
            @JsonProperty("ConditionMask") var ConditionMask: String = "",
            @JsonProperty("ValidateCode") var ValidateCode: String = "",
            @JsonProperty("Status") var Status: String = "",
            @JsonProperty("DayAmountLimit") var DayAmountLimit: String = "",
            @JsonProperty("DayAmount") var DayAmount: String = "",
            @JsonProperty("LastBidTime") var LastBidTime: String? = null,
            @JsonProperty("SettingUpdateTime") var SettingUpdateTime: String = "")
}
/*
{
  "status": 0,
  "msg": "OK",
  "count": 2,
  "sys": [
    {
      "StrategyId": "10",
      "UserId": "10",
      "StrategyLevel": "0",
      "StrategyName": "跻身名流",
      "Description": "我的策略描述",
      "AmountA": "-1",
      "AmountB": "-1",
      "MonthA": "-1",
      "MonthB": "-1",
      "RateA": "20.00",
      "RateB": "20.00",
      "Credit": "12",
      "CertificateValidate": "1",
      "CreditValidate": "1",
      "EducateValidate": "0",
      "VideoValidate": "0",
      "PhoneValidate": "0",
      "NciicIdentityCheck": "0",
      "Degree": "15",
      "StudyStyle": "7",
      "School": "5",
      "Gender": "3",
      "Age": "3",
      "LastSuccessIntervalA": "-1",
      "LastSuccessIntervalB": "-1",
      "FirstSuccessIntervalA": "-1",
      "FirstSuccessIntervalB": "-1",
      "SuccessCountA": "-1",
      "SuccessCountB": "-1",
      "WasteCountA": "-1",
      "WasteCountB": "-1",
      "NormalCountA": "-1",
      "NormalCountB": "-1",
      "NormalSuccessRatioA": "-1.00",
      "NormalSuccessRatioB": "-1.00",
      "DelayNormalRatioA": "-1.00",
      "DelayNormalRatioB": "-1.00",
      "OverdueCountA": "-1",
      "OverdueCountB": "-1",
      "OverdueMoreCountA": "-1",
      "OverdueMoreCountB": "-1",
      "OwingAmountA": "-1.00",
      "OwingAmountB": "-1.00",
      "OwingPrevHighDebtRatioA": "-1.00",
      "OwingPrevHighDebtRatioB": "-1.00",
      "OwingHighDebtRatioA": "-1.00",
      "OwingHighDebtRatioB": "-1.00",
      "LastHighestBorrowRatioA": "-1.00",
      "LastHighestBorrowRatioB": "-1.00",
      "BidAmount": "50",
      "ConditionMask": "128509836",
      "ValidateCode": "3",
      "Status": "0",
      "DayAmountLimit": "0",
      "DayAmount": "0",
      "LastBidTime": null,
      "SettingUpdateTime": "2017-10-01 23:47:51"
    },
    {
      "StrategyId": "11",
      "UserId": "10",
      "StrategyLevel": "0",
      "StrategyName": "青春学历",
      "Description": "测试策略",
      "AmountA": "-1",
      "AmountB": "-1",
      "MonthA": "-1",
      "MonthB": "-1",
      "RateA": "20.00",
      "RateB": "20.00",
      "Credit": "14",
      "CertificateValidate": "1",
      "CreditValidate": "1",
      "EducateValidate": "1",
      "VideoValidate": "0",
      "PhoneValidate": "0",
      "NciicIdentityCheck": "0",
      "Degree": "7",
      "StudyStyle": "7",
      "School": "7",
      "Gender": "3",
      "Age": "31",
      "LastSuccessIntervalA": "-1",
      "LastSuccessIntervalB": "-1",
      "FirstSuccessIntervalA": "-1",
      "FirstSuccessIntervalB": "-1",
      "SuccessCountA": "-1",
      "SuccessCountB": "-1",
      "WasteCountA": "-1",
      "WasteCountB": "-1",
      "NormalCountA": "-1",
      "NormalCountB": "-1",
      "NormalSuccessRatioA": "-1.00",
      "NormalSuccessRatioB": "-1.00",
      "DelayNormalRatioA": "-1.00",
      "DelayNormalRatioB": "-1.00",
      "OverdueCountA": "-1",
      "OverdueCountB": "-1",
      "OverdueMoreCountA": "-1",
      "OverdueMoreCountB": "-1",
      "OwingAmountA": "-1.00",
      "OwingAmountB": "-1.00",
      "OwingPrevHighDebtRatioA": "-1.00",
      "OwingPrevHighDebtRatioB": "-1.00",
      "OwingHighDebtRatioA": "-1.00",
      "OwingHighDebtRatioB": "-1.00",
      "LastHighestBorrowRatioA": "-1.00",
      "LastHighestBorrowRatioB": "-1.00",
      "BidAmount": "50",
      "ConditionMask": "1069081486",
      "ValidateCode": "7",
      "Status": "0",
      "DayAmountLimit": "0",
      "DayAmount": "0",
      "LastBidTime": null,
      "SettingUpdateTime": "2017-10-05 18:54:25"
    }
  ]
}
 */